"""edit langauge

Revision ID: 5695c9a52502
Revises: c42ef019a6b7
Create Date: 2026-09-14 23:39:05.433890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5695c9a52502'
down_revision: Union[str, Sequence[str], None] = 'c42ef019a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('language', sa.String(), nullable=True))
    op.add_column('language', sa.Column('degree', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'degree')
    op.drop_column('language', 'language')
    # ### end Alembic commands ###
