"""add design table

Revision ID: 6faa479ac1f3
Revises: 3649005930a9
Create Date: 2026-10-01 16:05:42.534886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6faa479ac1f3'
down_revision: Union[str, Sequence[str], None] = '3649005930a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desing_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('heading_title_color', sa.String(length=100), nullable=True),
    sa.Column('entry_title_color', sa.String(length=100), nullable=True),
    sa.Column('font', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desing_info_resume_id'), 'desing_info', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desing_info_resume_id'), table_name='desing_info')
    op.drop_table('desing_info')
    # ### end Alembic commands ###
