"""device_id row created tp refresh_token

Revision ID: b01ebcfd3f7f
Revises: d06bdc9bf222
Create Date: 2026-08-30 18:19:46.416238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01ebcfd3f7f'
down_revision: Union[str, Sequence[str], None] = 'd06bdc9bf222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('device_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_refresh_token_device_id'), 'refresh_token', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_device_id'), table_name='refresh_token')
    op.drop_column('refresh_token', 'device_id')
    # ### end Alembic commands ###
