"""backend modellar front typelarga moslandi 

Revision ID: ca7579c78fb6
Revises: 845f13a0ce70
Create Date: 2026-09-16 21:03:03.966068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7579c78fb6'
down_revision: Union[str, Sequence[str], None] = '845f13a0ce70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('startDate', sa.String(), nullable=True))
    op.add_column('education', sa.Column('endDate', sa.String(), nullable=True))
    op.drop_column('education', 'start_date')
    op.drop_column('education', 'end_date')
    op.add_column('experience', sa.Column('position', sa.String(), nullable=True))
    op.add_column('experience', sa.Column('company', sa.String(), nullable=True))
    op.add_column('experience', sa.Column('startDate', sa.String(), nullable=True))
    op.add_column('experience', sa.Column('endDate', sa.String(), nullable=True))
    op.drop_column('experience', 'start_date')
    op.drop_column('experience', 'postion')
    op.drop_column('experience', 'compony')
    op.drop_column('experience', 'end_date')
    op.add_column('resume', sa.Column('fullname', sa.String(), nullable=True))
    op.drop_column('resume', 'fullName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('fullName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('resume', 'fullname')
    op.add_column('experience', sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('compony', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('postion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('experience', sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('experience', 'endDate')
    op.drop_column('experience', 'startDate')
    op.drop_column('experience', 'company')
    op.drop_column('experience', 'position')
    op.add_column('education', sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('education', 'endDate')
    op.drop_column('education', 'startDate')
    # ### end Alembic commands ###
