"""UserSession table set device_id row

Revision ID: d06bdc9bf222
Revises: 864e48f3883a
Create Date: 2026-08-30 15:13:02.726741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06bdc9bf222'
down_revision: Union[str, Sequence[str], None] = '864e48f3883a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('device_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_sessions_device_id'), 'user_sessions', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_device_id'), table_name='user_sessions')
    op.drop_column('user_sessions', 'device_id')
    # ### end Alembic commands ###
