export const languages = [
  "Uzbek",
  "English",
  "Russian",
  "Chinese",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Arabic",
  "Japanese",
  "Korean",
  "Turkish",
  "Hindi",
  "Persian",
  "Kazakh",
  "Kyrgyz",
  "Tajik",
  "Turkmen",
  "Ukrainian",
  "Polish",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Czech",
  "Greek",
  "Hebrew",
] 

export const professions = [
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Mobile Developer',
  'iOS Developer',
  'Android Developer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Software Engineer',
  'Software Architect',
  'QA Engineer',
  'QA Automation Engineer',
  'Manual QA Tester',
  'Test Engineer',
  'Data Analyst',
  'Data Scientist',
  'Machine Learning Engineer',
  'AI Engineer',
  'AI Researcher',
  'Prompt Engineer',
  'Data Engineer',
  'Database Administrator',
  'Cybersecurity Engineer',
  'Security Analyst',
  'Information Security Specialist',
  'Cloud Security Engineer',
  'Blockchain Developer',
  'Web3 Developer',
  'Smart Contract Developer',
  'Game Developer',
  'Game Designer',
  'UI Designer',
  'UX Designer',
  'UI/UX Designer',
  'Product Designer',
  'Graphic Designer',
  'Motion Designer',
  '3D Artist',
  'Product Manager',
  'Project Manager',
  'Scrum Master',
  'Business Analyst',
  'System Analyst',
  'Technical Product Manager',
  'Technical Writer',
  'Solutions Architect',
  'IT Support Specialist',
  'System Administrator',
  'Network Engineer',
  'Site Reliability Engineer',
  'Release Engineer',
  'Build Engineer',
  'Embedded Systems Engineer',
  'Firmware Engineer',
  'Robotics Engineer',
  'IoT Engineer',
  'AR/VR Developer',
  'SEO Specialist',
  'Digital Marketing Specialist',
  'Content Manager',
  'Content Strategist',
  'Copywriter',
  'Technical Content Writer',
  'Social Media Manager',
  'Growth Marketer',
  'Performance Marketing Specialist',
  'Email Marketing Specialist',
  'Marketing Analyst',
  'Product Marketing Manager',
  'Sales Development Representative',
  'Business Development Manager',
  'Customer Success Manager',
  'Recruiter',
  'Technical Recruiter',
  'Talent Acquisition Specialist',
  'HR Specialist',
  'Operations Manager',
  'FinTech Specialist',
  'AI Product Manager',
  'AI Consultant',
  'Automation Engineer',
  'RPA Developer',
  'No-Code Developer',
  'Low-Code Developer',
  'Solutions Engineer',
  'Technical Consultant',
] 

export const skillCategories = [
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'Mobile Development',
  'UI/UX Design',
  'DevOps',
  'Cloud Computing',
  'Database Management',
  'Data Analysis',
  'Data Science',
  'Artificial Intelligence',
  'Machine Learning',
  'Cybersecurity',
  'Quality Assurance',
  'Test Automation',
  'Product Management',
  'Project Management',
  'Business Analysis',
  'Digital Marketing',
  'Graphic Design',
] 

export const skills = [
  // Programming languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'Go',
  'PHP',
  'Ruby',
  'Kotlin',
  'Swift',

  // Frontend
  'HTML',
  'CSS',
  'Vue.js',
  'Nuxt.js',
  'Angular',
  'Svelte',
  'Next.js',
  'Tailwind CSS',
  'Bootstrap',

  // Backend
  'Node.js',
  'Express.js',
  'NestJS',
  'FastAPI',
  'Django',
  'Flask',
  'Spring Boot',
  '.NET',

  // Databases
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'SQLite',

  // DevOps & Cloud
  'Docker',
  'Kubernetes',
  'GitHub Actions',
  'CI/CD',
  'AWS',
  'Google Cloud',
  'Microsoft Azure',
  'Linux',
  'Nginx',

  // Tools
  'Git',
  'GitHub',
  'GitLab',
  'REST API',
  'GraphQL',
  'WebSocket',
  'Postman',

  // AI & Data
  'Machine Learning',
  'Artificial Intelligence',
  'Data Analysis',
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',

  // Design
  'Figma',
  'UI/UX Design',
  'Responsive Design',

  // Professional skills
  'Problem Solving',
  'Communication',
  'Teamwork',
  'Leadership',
  'Project Management',
  'Agile',
  'Scrum'
] as const

export type  Language = typeof languages[number]